#!/bin/bash

# clean build script

rm cron.lock
rm -rfv cache
rm -rfv html/*.html html/*/*.html html/*/*/*.html
rm -rfv html/*.js html/*/*.js html/*/*/*.js
rm -rfv html/*.php html/*/*.php html/*/*/*.php
rm -rfv html/.htaccess
rm -rfv html/*.zip
rm -rfv html/rss.xml html/rss.txt
rm -rfv config/template/*
rm -rfv config/string/*

touch html/gracias.html
rm log/log.log

rm -rf html/txt/.git
mkdir -p html/txt
cd html/txt
git init
git add *
git commit -m "rebuild"
cd -
time ./build.sh
