#!/bin/bash

# clean build script

rm -rfv cache
rm -rfv html/*.html html/*/*.html html/*/*/*.html
touch html/gracias.html
rm log/log.log 

cd html/txt
git init
git add *
git commit -m "rebuild"
cd -
time ./rebuild.sh
