#!/bin/bash

# clean build script

rm cron.lock
rm -rf cache
rm -rf html/*.html html/*/*.html html/*/*/*.html
rm -rf html/*.js html/*/*.js html/*/*/*.js
rm -rf html/*.php html/*/*.php html/*/*/*.php
rm -rf html/.htaccess
rm -rf html/*.zip
rm -rf html/rss.xml html/rss.txt
rm -rf config/template/*
rm -rf config/string/*

touch html/gracias.html
rm log/log.log

rm -rf html/txt/.git
mkdir -p html/txt
cd html/txt
git init
git add *
git commit -m "rebuild"
cd -
time ./build.sh
