hike
====
a prototype distributed message board

access.pl
=========
reads the access log from the web server and parses actions submitted by clients.

supported formats are apache and lighttpd.

index.pl
========
takes the files in txt/, log/, and config/ and generates a sqlite database

generate.pl
===========
takes the database generated by index.pl and generates html files in html/

lighttpd.pl
===========
starts an instance of lighttpd using lighttpd.conf, which runs on port 3000

validate.pl
===========
currently doesn't do anything